// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1e-tLsYcri5GNEdHW-ITQZKq-Qh0Nqno',
    appId: '1:840350427511:web:2b0df38c35ae90e87f9972',
    messagingSenderId: '840350427511',
    projectId: 'habitarena-44863',
    authDomain: 'habitarena-44863.firebaseapp.com',
    storageBucket: 'habitarena-44863.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXYG2sM17_-Y_k2awpvr-obu4Yp_RJKC4',
    appId: '1:840350427511:android:320a6aa09eb7bf427f9972',
    messagingSenderId: '840350427511',
    projectId: 'habitarena-44863',
    storageBucket: 'habitarena-44863.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnq0iID7g-oganbI-b-RTwg-vlrhsOdYY',
    appId: '1:840350427511:ios:0d94b3d374b5ec647f9972',
    messagingSenderId: '840350427511',
    projectId: 'habitarena-44863',
    storageBucket: 'habitarena-44863.firebasestorage.app',
    iosBundleId: 'com.habitarena.habitArena',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnq0iID7g-oganbI-b-RTwg-vlrhsOdYY',
    appId: '1:840350427511:ios:0d94b3d374b5ec647f9972',
    messagingSenderId: '840350427511',
    projectId: 'habitarena-44863',
    storageBucket: 'habitarena-44863.firebasestorage.app',
    iosBundleId: 'com.habitarena.habitArena',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1e-tLsYcri5GNEdHW-ITQZKq-Qh0Nqno',
    appId: '1:840350427511:web:371f859d0f27653d7f9972',
    messagingSenderId: '840350427511',
    projectId: 'habitarena-44863',
    authDomain: 'habitarena-44863.firebaseapp.com',
    storageBucket: 'habitarena-44863.firebasestorage.app',
  );
}
